### ISSUE TITLE
DAX Syntax Highlighting for Docs

### ISSUE THREAD

**Issue by thedaxshepherd** [DaxStudio/DaxStudio-Docs#2]
I was hoping I could put this in discussions but it is turned off for this repository. It really is not an issue just something that could be helpful.

For all the DAX code in the documentation, there is no syntax highlighting. Luckily Docusaurus supports DAX and Power Query (not really applicable to the site but good to know it is there too) but you have to specify in the config file the additional languages.

docusaurus.config.js file:
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
		    additionalLanguages: ['dax'], 
      },

**Comment by dgosbell** [comment]
Thanks for logging this, I had looked at the standard syntax highlighting options, but I did not realize there was an existing DAX option that was so easy to implement. This is done and should be available in a few minutes once the automated deployment completes
